-- For the OLAP Process

SELECT PRESENTING_YEAR,VLE_MATERIAL_TYPE,TOTAL_NO_OFDAYS FROM TMP_FACT_TABLE2;

SELECT PRESENTING_YEAR,VLE_MATERIAL_TYPE,TOTAL_SUMCLICKS FROM TMP_FACT_TABLE2;

DROP TABLE FOR_VISUALIZATION;

CREATE TABLE FOR_VISUALIZATION AS SELECT VLE_MATERIAL_TYPE,TOTAL_NO_OFDAYS AS COLUMN1 FROM TMP_FACT_TABLE2 WHERE PRESENTING_YEAR = '2020';

DROP TABLE FOR_VISUALIZATION1;

CREATE TABLE FOR_VISUALIZATION1 AS SELECT VLE_MATERIAL_TYPE,TOTAL_NO_OFDAYS AS COLUMN2 FROM TMP_FACT_TABLE2 WHERE PRESENTING_YEAR = '2021';

DROP TABLE FOR_VISUALIZATION2;

CREATE TABLE FOR_VISUALIZATION2 AS SELECT FV.VLE_MATERIAL_TYPE,COLUMN1,COLUMN2 FROM FOR_VISUALIZATION FV, FOR_VISUALIZATION1 FV1 WHERE 
FV.VLE_MATERIAL_TYPE = FV1.VLE_MATERIAL_TYPE ;

DROP TABLE FOR_VISUALIZATION3;

CREATE TABLE FOR_VISUALIZATION3 AS SELECT VLE_MATERIAL_TYPE, ROUND((((COLUMN2-COLUMN1)/COLUMN1) * 100), 2) AS PERCENTAGE_INCREASE FROM FOR_VISUALIZATION2;

SELECT * FROM FOR_VISUALIZATION3