-- For the SCD Process
-- For SCD Implemantation, here we use TYPE 4

DROP TABLE HISTORY_TABLE

CREATE TABLE HISTORY_TABLE(
 VLE_ID NUMBER,
 PREVIOUS_VLE_MATERIALTYPE VARCHAR(60),
 ROW_EFFECTIVE_DATE DATE,
 ROW_EXPIRATION_DATE DATE,
 CURRENT_ROW_INDICATOR VARCHAR(20)
);

DROP TRIGGER TABLETRIGGERFOR_SCD;

CREATE OR REPLACE TRIGGER TABLETRIGGERFOR_SCD
AFTER INSERT OR UPDATE ON VLE_DIM
FOR EACH ROW
DECLARE Now TIMESTAMP;
BEGIN
SELECT CURRENT_TIMESTAMP INTO Now From Dual;
 INSERT INTO HISTORY_TABLE
 (VLE_ID, PREVIOUS_VLE_MATERIALTYPE, ROW_EFFECTIVE_DATE, ROW_EXPIRATION_DATE,
CURRENT_ROW_INDICATOR)
 VALUES
 (:OLD.VLE_ID, :OLD.PREVIOUS_VLE_MATERIALTYPE,:OLD.ROW_EFFECTIVE_DATE, SYSDATE,
'USING_FINISHED');
END;

UPDATE VLE_DIM
SET
PREVIOUS_VLE_MATERIALTYPE = 'OUWIKI',
CURRENT_VLE_MATERIALTYPE = 'OUWIKI_VERSION2',
ROW_EFFECTIVE_DATE = sysdate,
ROW_EXPIRATION_DATE = '12/31/9999',
CURRENT_ROW_INDICATOR ='CURRENTLY_USING'
WHERE CURRENT_VLE_MATERIALTYPE = 'OUWIKI'
