/*For the SS implementation*/
--------------------------------------------------------------
-- Database creation Script
-- Auto-Generated by QSEE-SuperLite (c) 2001-2004 QSEE-Technologies Ltd.
-- Verbose generation: ON
-- note: spaces within table/column names have been replaced by underscores (_)
-- Target DB: SQL2
-- Entity Model :Entity Relationship Diagram
-- To drop the tables generated by this script run -

--------------------------------------------------------------
-- Drop Table --
DROP TABLE FACT_TABLE cascade constraints;
DROP TABLE TIME_DIM cascade constraints;
DROP TABLE VLE_DIM cascade constraints;
--------------------------------------------------------------
-- Table Creation --
-- Each entity on the model is represented by a table that needs to be created within the Database --
-- Within SQL new tables are created using the CREATE TABLE command.
-- When a table is created its name and its attributes are defined.
-- The values of which are derived from those specified on the model.
-- Certain constraints are sometimes also specified, such as identification of primary keys.
-- Create a Database table to represent the "FACT_TABLE" entity.

CREATE TABLE FACT_TABLE(
 fact_id INTEGER NOT NULL,
 fk1_vle_id INTEGER NOT NULL,
 fk2_time_id INTEGER NOT NULL,
 no_of_days INTEGER,
 total_sumClicks INTEGER,
 -- Specify the PRIMARY KEY constraint for table "FACT_TABLE".
 -- This indicates which attribute(s) uniquely identify each row of data.
 CONSTRAINT pk_FACT_TABLE PRIMARY KEY (fact_id)
);
-- Create a Database table to represent the "TIME_DIM" entity.
CREATE TABLE TIME_DIM(
 time_id INTEGER NOT NULL,
 the_year INTEGER,
 -- Specify the PRIMARY KEY constraint for table "TIME_DIM".
 -- This indicates which attribute(s) uniquely identify each row of data.
 CONSTRAINT pk_TIME_DIM PRIMARY KEY (time_id)
);
-- Create a Database table to represent the "VLE_DIM" entity.
CREATE TABLE VLE_DIM(
 vle_id INTEGER NOT NULL,
 previous_vle_materialType VARCHAR(60),
 current_vle_materialType VARCHAR(60),
 row_effective_date DATE,
 row_expiration_date DATE,
 current_row_indicator VARCHAR(12),
 -- Specify the PRIMARY KEY constraint for table "VLE_DIM".
 -- This indicates which attribute(s) uniquely identify each row of data.
 CONSTRAINT pk_VLE_DIM PRIMARY KEY (vle_id)
);
--------------------------------------------------------------
-- Alter Tables to add fk constraints --
-- This constraint ensures that the foreign key of table "FACT_TABLE"
-- correctly references the primary key of table "VLE_DIM"
ALTER TABLE FACT_TABLE ADD CONSTRAINT fk1_FACT_TABLE_to_VLE_DIM FOREIGN KEY(fk1_vle_id) REFERENCES VLE_DIM(vle_id) ;

 -- Alter table to add new constraints required to implement the "FACT_TABLE_TIME_DIM" relationship
-- This constraint ensures that the foreign key of table "FACT_TABLE"
-- correctly references the primary key of table "TIME_DIM"
ALTER TABLE FACT_TABLE ADD CONSTRAINT fk2_FACT_TABLE_to_TIME_DIM FOREIGN KEY(fk2_time_id) REFERENCES TIME_DIM(time_id);
--------------------------------------------------------------
-- End of DDL file auto-generation --